dark_mode:
  enable: true
  default: dark

favicon: /favicon.ico
index:
  slogan:
    text: "zjlhhh123's note"

about:
  avatar: https://x.boardgamearena.net/data/avatar/defaults/default-0915.jpg
  name: "zjlhhh123"
  intro: "A Software Engineer"
  icons:
    - { class: "iconfont icon-github-fill", link: "https://github.com/asdf0123", tip: "GitHub" }
    - { class: "iconfont icon-mail", link: "mailto:zjlhhh123@outlook.com", tip: "Outlook" }
    - { class: "iconfont icon-mobile", link: "tel:+8617710703750", tip: "Phone (+86, overseas calls may be blocked)" }
    - { class: "iconfont icon-qq-fill", link: "tencent://message/?uin=2469197864&&Site=&Menu=yes", tip: "Tencent QQ" }
    